version: '3.8'

services:
  db:
    image: postgres:15
    container_name: bgtour_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bgtour
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    container_name: bgtour_backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      DATABASE_URL: postgres://postgres:postgres@db:5432/bgtour?sslmode=disable
      JWT_SECRET: changemeplease
      PIN_EXPIRATION_MINUTES: 30

  frontend:
    build: ./frontend
    container_name: bgtour_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data: